"""
SMS Slang Lexicon Dictionary
Common informal abbreviations used in SMS messages mapped to standard English.
"""

SLANG_DICT = {
    # Pronouns / common words
    "u": "you",
    "ur": "your",
    "r": "are",
    "b": "be",
    "y": "why",
    "k": "ok",
    "m": "am",
    "n": "and",
    "2": "to",
    "4": "for",
    "4u": "for you",
    "b4": "before",
    "2day": "today",
    "2nite": "tonight",
    "2moro": "tomorrow",
    "2morrow": "tomorrow",
    "2mrw": "tomorrow",
    "4got": "forgot",
    "4ever": "forever",
    "2gether": "together",
    # Greetings / expressions
    "gm": "good morning",
    "gn": "good night",
    "gud": "good",
    "gr8": "great",
    "g8": "great",
    "lol": "laugh out loud",
    "lmao": "laugh my ass off",
    "rofl": "rolling on the floor laughing",
    "omg": "oh my god",
    "omfg": "oh my god",
    "wtf": "what the hell",
    "wth": "what the hell",
    "idk": "i do not know",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "tbh": "to be honest",
    "ngl": "not gonna lie",
    "fyi": "for your information",
    "iirc": "if i recall correctly",
    "irl": "in real life",
    "jk": "just kidding",
    "jfyi": "just for your information",
    "btw": "by the way",
    "brb": "be right back",
    "bbl": "be back later",
    "bbs": "be back soon",
    "afk": "away from keyboard",
    "imo": "in my opinion",
    "np": "no problem",
    "np": "no problem",
    "yw": "you are welcome",
    "ty": "thank you",
    "thx": "thanks",
    "thnx": "thanks",
    "tnx": "thanks",
    "tx": "thanks",
    "pls": "please",
    "plz": "please",
    "plx": "please",
    "sry": "sorry",
    "srry": "sorry",
    "nvm": "never mind",
    "nvr": "never",
    "evr": "ever",
    "wut": "what",
    "wut": "what",
    "wats": "what is",
    "wat": "what",
    "abt": "about",
    "hw": "how",
    "hows": "how is",
    "hw r u": "how are you",
    "hru": "how are you",
    "wen": "when",
    "whr": "where",
    "wer": "where",
    "der": "there",
    "dere": "there",
    "dis": "this",
    "dat": "that",
    "dats": "that is",
    "d": "the",
    "da": "the",
    "de": "the",
    "dem": "them",
    "dey": "they",
    # Short words
    "txt": "text",
    "msg": "message",
    "msgs": "messages",
    "mob": "mobile",
    "mob": "mobile",
    "mobi": "mobile",
    "nite": "night",
    "nyt": "night",
    "tmrw": "tomorrow",
    "tmr": "tomorrow",
    "tmo": "tomorrow",
    "asap": "as soon as possible",
    "atm": "at the moment",
    "b4n": "bye for now",
    "cya": "see you",
    "cya": "see you",
    "cu": "see you",
    "cul8r": "see you later",
    "l8r": "later",
    "l8": "late",
    "l8": "late",
    "ltr": "later",
    "ttyl": "talk to you later",
    "ttys": "talk to you soon",
    "tty": "talk to you",
    "tc": "take care",
    "wanna": "want to",
    "gonna": "going to",
    "gotta": "got to",
    "kinda": "kind of",
    "sorta": "sort of",
    "dunno": "do not know",
    "lemme": "let me",
    "gimme": "give me",
    "cmon": "come on",
    # Alphanumeric slang
    "b2b": "business to business",
    "c2c": "customer to customer",
    "1st": "first",
    "2nd": "second",
    "3rd": "third",
    "w8": "wait",
    "h8": "hate",
    "m8": "mate",
    "sk8": "skate",
    "sk8r": "skater",
    "d8": "date",
    "f8": "fate",
    # Spam-related common slang
    "ur": "your",
    "fre": "free",
    "frm": "from",
    "mob": "mobile",
    "cs": "customer service",
    "wk": "week",
    "wkly": "weekly",
    "mth": "month",
    "yr": "year",
    "min": "minute",
    "mins": "minutes",
    "hr": "hour",
    "hrs": "hours",
    "wk": "week",
    "wks": "weeks",
    "acc": "account",
    "acct": "account",
    "amt": "amount",
    "cd": "could",
    "gt": "got",
    "hav": "have",
    "hve": "have",
    "nd": "and",
    "sm": "some",
    "sme": "some",
    "sumthing": "something",
    "sumthng": "something",
    "sumthin": "something",
    "smthn": "something",
    "smth": "something",
    "ne1": "anyone",
    "ne": "any",
    "neway": "anyway",
    "anyways": "anyway",
    "nething": "anything",
    "evry1": "everyone",
    "every1": "everyone",
    "som1": "someone",
    "sum1": "someone",
    "no1": "no one",
    "1": "one",
    "dont": "do not",
    "doesnt": "does not",
    "cant": "cannot",
    "wont": "will not",
    "couldnt": "could not",
    "wouldnt": "would not",
    "shouldnt": "should not",
    "im": "i am",
    "ive": "i have",
    "id": "i would",
    "ill": "i will",
    "isnt": "is not",
    "arent": "are not",
    "wasnt": "was not",
    "werent": "were not",
    "havent": "have not",
    "hasnt": "has not",
    "hadnt": "had not",
    "didnt": "did not",
    "theyre": "they are",
    "theyd": "they would",
    "theyll": "they will",
    "theyve": "they have",
    "youre": "you are",
    "youd": "you would",
    "youll": "you will",
    "youve": "you have",
    "hes": "he is",
    "shes": "she is",
    "its": "it is",
    "weve": "we have",
    "wed": "we would",
    "well": "we will",
    # Spam-specific terms
    "priz": "prize",
    "prizewinner": "prize winner",
    "pr1ze": "prize",
    "fr33": "free",
    "fr3e": "free",
    "w1n": "win",
    "c1ick": "click",
    "cl1ck": "click",
    "c0st": "cost",
    "cust": "customer",
    "custmr": "customer",
    "subcrib": "subscribe",
    "subscrib": "subscribe",
    "unsubscrib": "unsubscribe",
    "reciev": "receive",
    "recive": "receive",
    "receve": "receive",
    "reedem": "redeem",
    "redeme": "redeem",
    "rply": "reply",
    "rpl": "reply",
    "stop2": "stop to",
    "stp": "stop",
    "nt": "not",
    "nw": "now",
    "nxt": "next",
    "nw": "now",
    "ppl": "people",
    "pepl": "people",
    "pe0ple": "people",
    "mrkt": "market",
    "mkt": "market",
    "dlr": "dollar",
    "dlrs": "dollars",
    "grt": "great",
    "gr8t": "great",
    "amzing": "amazing",
    "amazin": "amazing",
    "specia1": "special",
    "exclu5ive": "exclusive",
    "exclusiv": "exclusive",
    "xclusiv": "exclusive",
}
